spring:
  mail:
    host: smtp.gmail.com
    username: testsocialeventorg@gmail.com
    password: PRO_password1!
    port: 587
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: true
  #  datasource:
  #    driver-class-name: org.postgresql.Driver
  #    url: jdbc:postgresql://172.21.40.109:5432/test_db
  #    username: postgres
  #    password: SocEventOrgDB
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#    data: classpath:import.sql
#    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logbook:
  filter.enabled: true
  format.style: http
  write:
    max-body-size: 1000

final:
  project:
    testProperty: siemanko

